Repository github-quest/github-quest.github.io, pull requests merged in 2022-10, with the labels that each got.

#46 Added some comments
  index.html
Labels: documentation, hacktoberfest-accepted

#49 removed home.html
  home.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, bugfix

#51 Updated Contact Page
  contact.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, html

#54 Updated Year in footer
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#55 fix: update year in contactPage footer
  contact.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#56 Align Contributors to Center
  contact.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#57 added linkedin profile to the list of contributors
  contact.html
Labels: hacktoberfest-accepted, html

#60 added div around the Heading font
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, html

#61 Added the Video Of Eddie Jaoude for getting started to open source for first timers
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#62 Added Git Tutorial Link and Hacktoberfest Link
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#63 Redesigned with new color scheme
  contact.html
  css/styles.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#64 content redesign
  contact.html
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, html
